### PR TITLE
[wip] clean up

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Bug Fix? | n |
| New Feature? | n |
| BC Breaks? | n |
| Deprecations? | n |
| Tests Pass? | n |
| Fixed Tickets |  |
| License | MIT |
| Doc PR |  |

 Sent using [Gush](https://github.com/gushphp/gush)

### CODE REVIEW

**Comment by sdboyer** [comment]
whatever you were aiming for with this didn't work. (clearly)

some explanation would be helpful.

**Comment by cordoval** [comment]
it says is a wip

**Comment by sdboyer** [comment]
so you're asking me to ignore this until you remove the wip from the title?

**Comment by cordoval** [comment]
oh no, sorry did not mean to sound rude

ok let me explain: I actually have to start work in 6 minutes but:

So all started on drupal.org with your excellent work on the Assetic integration, then I went and saw that you had plugged two libraries, then checked each library, one of them is this one, so in order to get acquainted i usually scan the code and do some fixes, and improvements.

**Comment by cordoval** [comment]
So basically this is wip because I noticed the other library frozen and also needed to jump on drupal again to check composer and stuff, i am doing a series at http://craftitonline.com/ you may read for more details. This PR is wip and we can easily make it work, it would be just an upgrade to PSR-4 and fixing failing tests. It should be simple, and maybe more. However because of time constraints I will take a look at this after I come back to my country.

**Comment by sdboyer** [comment]
ok, thanks, that's the context i needed. scanned the most recent post - my github fork _should_ be up to date with the latest patch; if it isn't, it's just because i was lazy with the last patch or two. though, as you noted, that history is long and windy, with many core merges and lots of weird stuff in there.

i don't mind the cleanup at all, and converting to PSR-4 is perfectly fine. and if adding that autoload directive means i don't have to have my own bootstrap.php, then great.

maybe i'll actually finish that patch sometime. heh.

**Comment by sdboyer** [comment]
any chance of cleaning this up?

**Comment by cordoval** [comment]
i fell sick :cry:

**Comment by cordoval** [comment]
closing for now :older_man:

**Pull request closed without merging**
